language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=coverage
  - TOXENV=flake8
  - TOXENV=docs
install:
  - pip install tox
script:
  - tox
