language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
- pypy3
- nightly
matrix:
  include:
  - python: 2.7
    env: TOXENV=flake8
  - python: 2.7
    env: TOXENV=docs
  - python: 3.5
    env: TOXENV=coverage
  - python: 3.5
    env: TOXENV=flake8
  - python: 3.5
    env: TOXENV=docs
install:
  - pip install tox-travis
script:
  - tox
